# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target "StupidFramework" do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "AYCategory"
  pod "AYPromise"
  pod "AYQuery"
  pod "AYFile"
  pod "Masonry", "~> 1.0"
  pod "AFNetworking/Reachability", "~> 3.0"
  pod "AFNetworking/Serialization", "~> 3.0"
  pod "AFNetworking/Security", "~> 3.0"
  pod "AFNetworking/NSURLSession", "~> 3.0"
  pod "SVProgressHUD", "~> 2.0"
  pod "TZImagePickerController", "3.6.4"
  pod "GCDWebServer", "~> 3.0"
  pod "SQLCipher", "~>4.0"
  # Pods for Example
end
